### ISSUE TITLE
Request for payload ID "BUBBLE"

### ISSUE THREAD

**Issue by FelSchae** [projecthorus/horusbinary#13]
For Bubble missions by KSat: https://www.ksat-stuttgart.de/en/our-missions/bubble/

DG2FS

**Comment by darksidelemm** [comment]
As per the main README of this repo, this repository is now deprecated, with all further development occurring in https://github.com/projecthorus/horusdemodlib 
Please use the decoder codebase from that repository, or the new Horus-GUI demodulator: https://github.com/projecthorus/horus-gui

I've assigned payload ID 21 to BUBBLE in that repo. I've also made a payload document in Habitat (doc ID: 36cdb60c8492d5d504330024eda55b2c ) so the callsign should show up on the map once you start decoding. I did this by using the 'start from existing' option in genpayload ( http://habitat.habhub.org/genpayload/ ) and basing the document off another Horus Binary payload doc.

**Comment by FelSchae** [comment]
Thank you for the quick adding to the list.

Felix

Am 2020-08-02 14:46, schrieb Mark Jessop:

**Comment by darksidelemm** [comment]
Also, I noticed on the HabHub IRC channel that you are running your payload at 300 baud. This is NOT recommended.
The 4FSK system has been tested extensively at 100 baud, which gives you updates every 3 seconds, which is *more* than enough for regular tracking.
