### ISSUE TITLE
Payload ID

### ISSUE THREAD

**Issue by FoxnoTango** [projecthorus/horusbinary#14]
Dear OM,

I would like to request for a payload ID for the callsign: PA3FNT-4FSK

73 Foeke PA3FNT

**Comment by darksidelemm** [comment]
Hi,

I have assigned payload ID #22 to PA3FNT-4FSK, however this has occurred in the horusdemodlib repository ( https://github.com/projecthorus/horusdemodlib/blob/master/payload_id_list.txt ) as this repository is deprecated.

If you are using any demodulation code from this repository, I suggest you switch to the code in https://github.com/projecthorus/horusdemodlib or use horus-gui ( https://github.com/projecthorus/horusdemodlib/wiki/1.1-Horus-GUI-Reception-Guide-(Windows-Linux-OSX) )

73
Mark VK5QI
