### ISSUE TITLE
Please ID for my third balloon which will be soon launched, 9A4GE-3

### ISSUE THREAD

**Issue by WildMany** [projecthorus/horusbinary#15]
Hello. 
Plan is to send balloon when wind is toward west, but previous predictions on May, 1st and second are slightly north. Now, third day in May may be the "day", but I need third ID for 9A4GE-3.

Thank you in advance.
Milan, 9A4GE.

**Comment by darksidelemm** [comment]
Could you clarify please: Are you intending to have 3 balloons in the air all active simultaneously, or is this your third launch so far?
If this is just another launch, then please re-use your existing payload IDs. I don't want to allocate new IDs for every new launch, only if you expect to have multiple payloads in the air at the same time.

**Comment by WildMany** [comment]
> Could you clarify please: Are you intending to have 3 balloons in the air all active simultaneously, or is this your third launch so far? If this is just another launch, then please re-use your existing payload IDs. I don't want to allocate new IDs for every new launch, only if you expect to have multiple payloads in the air at the same time.

It will be almost simultaneously. Solar power, and it should last for few days. Forgot to mention, Horus V2.
73

**Comment by darksidelemm** [comment]
OK, fine, all done:
```
569, 9A4GE-3
```

**Comment by WildMany** [comment]
> OK, fine, all done:
> 
> ```
> 569, 9A4GE-3
> ```

Thanks!73 de 9A4GE, Milan
---
