### ISSUE TITLE
Got payload ID, but it does not work properly.

### ISSUE THREAD

**Issue by WildMany** [projecthorus/horusbinary#16]
Hello. 
Got payload id for 9A4GE-3, that is 569, but it does not works properly - showing "Unknown_payload_ID"

What I am doing wrong. So far, all my other IDs working great, except that last one. Please check.

Thank you in advance.

73, Milan, 9A4GE

**Comment by darksidelemm** [comment]
You will need to restart your decoders and make sure your payload ID lists
update on startup.

**Comment by WildMany** [comment]
Oh, yes. Thanks!
